#The core of this code was taken from Computational Physics - Electromagnetism by Jamie Flux. Changes from the original code and interjections of code of my own or from other online sources may be present. Comments are all by me
#This is one of my first python projects so the goal is to take a snippet of efficient code from a professional and understand what it means and why it works. That is why there is such excessive commenting


import numpy as np #Imports NumPy library (used for matrix computation)
from numba import njit, prange # Numba is similar to NumPy but in certain contexts has speed and memory advantages over NumPy. For optimization, this code uses a combination of NumPy and Numba
# njit ("no-python JIT" [Just in Time]) is a decorator 



# Define vector with user input
user_input = input("Enter a 1 to 3 dimensional Vector: ") 
#Vector = user_input.split() 
    # Split method scans a string (here one inputted by the user) and returns a list of substrings (here this corresponds to characters seperated by whitespace)

#Vector = np.array(user_input.split(), dtype=float)
    #  #This line does same thing as above, but the utilization of NumPy creates effieiceny. Python stores lists as arrays of pointers (variable which stores information on the location of a different variable, seperate from the variable itself, [The variable itself is NOT stored in the array, the array simply stores address information as non-contiguous {Contiguous meaning memory stored as single, unbroken blocks, where each element is physically stored next to each other in the RAM} objects "PyObject Structures", which are stored anywhere in the heap {anywhere because it's non-contiguous}]).
    #In CS, variables contain two sets of information: Label (name [e.g. vectorA] & pointer [address information]) & Content (value e.g. 2)
    #NumPy also uses pointers, but a NumPy array has only one pointer, whereas a Python array has a pointer for every element of the array.
    #A NumPy pointer uses Memory Striding to store address info of a list of variables using only one pointer.
    #NumPy array's are contiguous and homogeneous (all address info is same size)
    #Each NumPy array has a "header", a block of metadata in the Stack (Section of RAM dedicated to Static Memory Allocation [Static Memory being data allocated during compile-time {before program runs} and NOT run-time] and execution tracking ["The Call Stack", how the computer remembers where it is in your code during execution]), containing four pieces of information:
            #1.) Data Pointer
            #2.) Dtype (Data Type): size of each element (eg float, double, etc.) *! VARIABLE CONTENT (NOT ADDRESS INFO) MUST BE HOMOGENOUS TO USE NUMPY ARRAY/MEMORY STRIDING. This is why the function arg asks for dtype
            #3.) Shape: The Dimensions of the data (eg 3 x 2)
            #4.) Strides: The number of bytes you must skip to reach the next element in each dimension of the array
    #Memory striding is the use of the "rule" or metadata stored in an array header to traverse a contiguous block of data
    #Array's with memory striding are very useful because they are so efficient, but are not always usable because they only work with data of the same size. This is why a standard Python array does not use memory striding.


#Basic Vector Operat
# Split into strings, convert to floats, and cast to a NumPy array
try: #Try and Except are used for error handleing. Place the code you think might fail in the "try section", contingency plan goes under "except"
    Vector = np.array([float(i) for i in user_input.split()]) #Argument in square brackets is a method of creating lists using "List Comprehension" (cleaner look & more efficient compared to traditional loops). Here, for every element generated by user_input.split(), [float(i) for i in user_input.split()] converts every element value into a float (ensuring homogeneuity)
    print(f"Vector: {Vector}")
    print(f"Magnitude: {np.linalg.norm(Vector)}")
except ValueError: #ValueError is a type of exception that occurs when function has right type of input but incorrect value (eg sqrt of -1 in a real number function)
    print("Error: Please enter only numbers.")



# @njit 
# class Vector:
#     def __init__(self, x, y, z):
#         self.x = x
#         self.y = y
#         self.z = z

      
#     def __add__(self, other):
#         return Vector(self.x - other.x, self.y + other.y, self.z + other.z)   
#     def __sub__(self, other):
#         return Vector (self.x - other.x, self.y - other.y, self.z - other.z)
#     def __mul__(self, scalar):
#         return Vector(scalar * self.x, scalar * self.y, scalar * self.z)
#     def dot(self, other): 
#         return self.x * other.x + self.y * other.y + self.z * other.z
#     def cross(self, other):
#         cross_x = self.y * other.z - self.z * other.y
#         cross_y = self.z * other.x - self.x * other.z
#         cross_z = self.x * other.y - self.y * other.x
#         return Vector(cross_x,cross_y, cross_z)
#     def magnitude(self):
#         return np.sqrt(self.x*2 + self.y**2 + self.z**2)
#     def __repr__(self):
#         return f"Vector({self.x}, {self.y}, {self.z})"


